### ISSUE TITLE
New permission structure

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-permission-service#109]
```
agenda:
    can_manage:
        can_see_internal_items:
            can_see:
list_of_speakers:
    can_manage:
        can_see:
    can_be_speaker:
        can_see:
assignment:
    can_manage:
        can_nominate_other:
            can_see:
    can_nominate_self:
        can_see:
meeting:
    can_manage_logos_and_fonts:
    can_see_history:
    can_see_autopilot:
    can_see_frontpage:
    can_manage_settings:
    can_see_livestream: <-- NEU
projector:
    can_manage:
        can_see:
motion:
    can_manage:
        can_manage_metadata:
            can_see:
        can_create:
            can_see:
        can_create_amendments:
            can_see:
        can_see_internal:
            can_see:
        can_manage_polls:
            can_see:
    can_support:
        can_see:
mediafile:
    can_manage:
        can_see:
tag:
    can_manage:
user:
    can_manage:
        can_see_extra_data:
            can_see:
    can_change_own_password:
```
