### ISSUE TITLE
Committee managers must be able to see the committee members.

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-permission-service#133]

**Comment by ostcar** [comment]
Please be more specific.

Which fields can they see? Do they have the permission "user.can_see" in all meetings or is it something special? Maybe they have "user.can_manage"?

What about committee members? Can they see other members?

**Comment by normanjaeckel** [comment]
Committee managers can see some fields. I am not sure. Please double check.
```
  id: number
  username: string
  title: string
  first_name: string
  last_name: string
  is_active: boolean
  is_physical_person:
    type: boolean
    default: true
  gender: string
  email: string
  last_email_send: string
  is_demo_user:
    type: boolean
    read_only: true

  # Organisation, meeting and committee
  organisation_management_level:
    type: string
    description: Hierarchical permission level for the whole organisation.
    enum:
    - superadmin
    - can_manage_organisation
    - can_manage_users
  committee_as_member_ids:
    type: relation-list
    to: committee/member_ids
  committee_as_manager_ids:
    type: relation-list
    to: committee/manager_ids
```

Committee members can not see other members (they may see them via a meeting permission but this does not depend on their membership).
